### ISSUE TITLE
BASH: single line mode useless

### ISSUE THREAD

**Issue by vadviktor** [bullettrain-sh/bullettrain-go-core#17]
Using Linux, BASH, single line mode.

The prompt gets displayed in a way that it becomes completely useless. Only occurs when background colours are used, disabling them will make the prompt stable.

![selection_001](https://user-images.githubusercontent.com/238703/29665657-fa53f7da-88cc-11e7-9cca-862ea24e88aa.jpg)

**Comment by jtyr** [comment]
I saw that as well in both the Terminator and the Konsole.

**Comment by jtyr** [comment]
What about try try to close the escape sequences as described [here](https://superuser.com/questions/367275/linux-coloring-bash-prompt-will-break-carriage-return). All these bugs are very annoying.

**Comment by vadviktor** [comment]
Yes that would be the solution, it's just that those non-printing chars are shell only and have not yet found a way to "communicate" them via stdout.

**Comment by vadviktor** [comment]
Axing bash support for now.
