### ISSUE TITLE
Long commands sometimes vanish on typing

### ISSUE THREAD

**Issue by vadviktor** [bullettrain-sh/bullettrain-go-core#18]
In both ZSH and BASH sometimes when I'm typing long instructions, the line of text may become invisible for some reason.

**Comment by jtyr** [comment]
I have noticed this as well. But if I maximize the shell window the problem disappears. Is that something to do with the colors and their interpretation in the shell emulator? I have tested it in Terminator and Konsole.

**Comment by vadviktor** [comment]
I believe it has some connection to how the terminal emulators react to not having their "non-printing" characters added to the text. Simply I have not found a way to add `\[` and `\]` (tput sgr0) to surround the  colour codes (in ZSH they are `{%` and `}%`. Adding the ZSH ones make no difference to what I have observed. Some solid way of reproducing the issue would help.

**Comment by vadviktor** [comment]
I think, for ZSH I have fixed these by adding in the non-printing characters. 6b7b13be793bad4c2ce2f36a1e751ff8621fff83

For BASH though, adding I am not able to figure out how to add them :(
