### ISSUE TITLE
Path should display ~ not /home/user with in $HOME

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#23]
Title pretty much says it. When you are in your home directory you should see ~ not /home/user/ as your path.

**Comment by vadviktor** [comment]
Thanks @gregf for the suggestion, I'll work on it.

**Comment by gregf** [comment]
Just check if the current path = $HOME and then print ~ instead of the path.

**Comment by vadviktor** [comment]
Done in 74292d0
