### ISSUE TITLE
BULLETTRAIN_CAR_TIME_SYMBOL_PAINT effecting BULLETTRAIN_CAR_OS_SYMBOL_PAINT

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#25]
When setting BULLETTRAIN_CAR_TIME_SYMBOL_PAINT it also changes the color for BULLETTRAIN_CAR_OS_SYMBOL_PAINT

**Comment by vadviktor** [comment]
Fixed in #27
