### ISSUE TITLE
Setup glide or another vendor system

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#3]
It would be nice if you had [glide](https://github.com/Masterminds/glide) or something similar setup for development to pull in dependencies. It would make it a lot easier to get a development environment going.

**Comment by vadviktor** [comment]
Yes indeed. I used glider before and now I was trying out `go dep` as it is going to be part of the official go toolset. Though I found it nasty for rapid development for software as this one, with several related modules. The dependency file cared only for remote SHA IDs, not being able to attune for local ones. At least I did not want to spend hours setting them up.

Do you think glide will let us develop `core` with only local versions of the related modules?

**Comment by vadviktor** [comment]
I was wondering, when we reach the magic v1, we could use the `yyyy-mm` e.g. 2017-04 versioning as software that see updates frequently use nowadays.
Though I'd be interested how we could sync the other modules that won't need updating, like if the main API won't change and let's say the golang module won't need updating it could be like this:

core 2018-03 and golang 2017-10

Versioning every module with proper package manager is crucial I think. We'd need to be able to define the minimal version of core a module is compatible with.

**Comment by gregf** [comment]
I don't typically like that type of versioning but I think it makes sense here.

**Comment by vadviktor** [comment]
I'll hit up a new ticket when the v1 is getting closer. For now I merged PR #4 , thanks!
