### ISSUE TITLE
Format of the cars as a variable

### ISSUE THREAD

**Issue by jtyr** [bullettrain-sh/bullettrain-go-core#30]
The string produced by each car should be defined by some kind of template which would be possible to override via env variable. For example I would like to have each car in the following format:

```
{space}{icon}{space}{text}{space}
```

With the current setup, I have to override the icon and the separator env vars to include the spaces.

**Comment by vadviktor** [comment]
Personally, I don't see a need to add more complexity to the code. Spaces for me for example is not needed, BUT if some characters or some user's personal taste dictates it otherwise, it only requires a good documentation and intuition to know only the existing variables are needed to be tweaked.

**Comment by jtyr** [comment]
Fair enough. But there are certain situations where there is no such variable to use to insert a space where I need it. For example if my train is composed by cars `context dir`. How can I configure the `context` train to start with a space? Currently it's not possible and the only way how to achieve it is to change the `Sprintf("%s@%s", ...)` to have an extra space at the beginning. If the formatting string would be as a variable, or even better if it would be like a template `{space}{user}@{host}{space}`, it would allow me to configure whatever I want.

**Comment by vadviktor** [comment]
@jtyr thanks for pointing that edge case out, now I completely understand your point. Let me give your template suggestion a few days in the back of my head. Since I am still learning Go I have not yet looked at it's template lib. I will get back when I have a proposal of some sort.

**Comment by jtyr** [comment]
Please take your time. This feature should be well thought through. We probably still need some kind of variables to influence the parts of the template. If we take the example from above (`{space}{user}@{host}{space}`), it would probably be good to have variables for the `{user}` and `{host}` where each of them would be a subtemplate. Meaning that `{user}` would actually be `{user_login;white+b:black}` or it could also be `{user_comment;white+b:black}` or even `{user_id;white+b:black}`. Similarly the `{host}` could be `{host_short;green:white}` or `{host_fqdn;green:white}` or even `{host_ipv4;green:white}`. The color could be like another variable `{host_ipv4;{context_paint}}` so you can change the color for all elements with one variable.

It looks a bit overcomplicated but something like that would be really powerful and useful.

**Comment by vadviktor** [comment]
@gregf please take a look at this discussion. It could drive the next step for breaking apart the Context car.

**Comment by jtyr** [comment]
Or perhaps even the list of cars could be like a template:

```
{status}{context}{dir}{git}{prompt}
```

where for example `{context}` would be:

```
{space}{user}@{host}{space}
```

where `{host}` would be:

```
{host_short;{context_paint}}
```

where `{context_paint}` would be:

```
green+b:white
```

**Comment by vadviktor** [comment]
Now, this much of complication sounds the alarms in my head. This could start a snowball effect pretty quickly. Right now it's just a small amount you put in the examples but in general you are inventing a templating system. Which could be good in a web dev situation, but this is just simple text and parsing such templates takes time and introduces lag.
I only wish to add as little control as possible and don't wish to save the world.

Obviously the task here is first to be able to add spaces to surround the info text.

Second and optional task could be to rearrange some components within the text of a car. The {space}, probably a {symbol} and a {text} variable should do it. This could tell how to structure text, still let us identify what to colour (the "how" is in env vars already and their format is fine).

**Comment by vadviktor** [comment]
I'm looking into how we could use the built in text templating of Go https://golang.org/pkg/text/template/.

My first idea that the `{{space}}` and other variables could be used as "published" ones and like building blocks, the user could even rearrange text within the car, even put multiple instances of the info text, e.g. put an icon at the front and at the back of the info text :)

Though, I am still thinking about how much more logic needs to be added for painting them separately.

**Comment by gregf** [comment]
I really like the idea of using go templates to format the prompt.

**Comment by vadviktor** [comment]
This will be trickier I guess. E.g. the dir car has more to configure as the path separators, the path directories are moving parts too that can have optional spaces in between.
I myself really feel to need some good solution to this too, cramping multibyte chars are really annoying, like the train just crashed into a wall and got squeezed a bit.

**Comment by jtyr** [comment]
I would say that the only proper templating can help with this problem. Define a list of keywords which can be used in the car template and on the render time just simply replace all the keywords with their value.

**Comment by vadviktor** [comment]
I have looked into Go's template library. It offers so much that one could expect from a real template library. For us, it is only the variable substitution part that matters.  In Python, a plain str.format would do ;)

So, I will upgrade the standard/existing Cars to expose their information blocks and icons. Then the user can override it's printed form by using it's predefined names, Go template style.

e.g.:

the Time car could expose it's icon and printed text (time).

There are only 3 rules to follow: 
1. exposed names start with a dot, because they will internally be bundled within a struct
2. exposed names start with capital letter, because the struct needs to expose them and everything is exposed (aka public) in Go if it is capitalised
3. exposed names are enclosed in `{{` and `}}` as they are the Go template system's chosen delimiters

`{{.Icon}}` : the icon of the car
`{{.Time}}` : the information this car exposes

Then one could surround the car's output text with spaces to her liking:

` {{.Icon}} {{.Time}} `

Note the spaces between and at the beginning and end.

So the user can put those variables anywhere, EVEN leave one out. Which leads me to another question: should the more flexible template string take over e.g. the ICON_SHOW env vars?

**Comment by jtyr** [comment]
I think that each of the template strings (e.g. `{{.Icon}}`) should be represented by a variable (e.g. `BULLETTRAIN_CAR_TIME_SYMBOL_ICON`). The only exception is the generated text (e.g. `{{.Time }}`).

**Comment by vadviktor** [comment]
Sorry @jtyr I don't really understand what you are suggesting and what is it's source of idea.
Just to be clear, that .Icon variable will still hold the painted version of the defined icon, be it from the env variable or the default built in one. These template variables are only defining their place, nothing more.

**Comment by jtyr** [comment]
My imagination was that the format of the train will bi in an env variable:

```
BULLETTRAIN_CAR_TIME_FORMAT=" {{.Icon}} {{.Time}} "
```
And that we can influence the template strings via another variables:

```
BULLETTRAIN_CAR_TIME_ICON="@"
```

There is no env var for `.Time` as that's the value generated by the train.

**Comment by vadviktor** [comment]
Yes @jtyr  that's how I wanted to describe it as you just did, thanks! :) I feel a bit taxed in the past few weeks, that's why am a little slower too lately.

I also felt that the examples would be enough to describe this feature and is very much ready to see it in action (code). Since I am dogfooding it 24/7, I test the implementation's UX too. I'll get back to you when I have something to report, and my plan is to create a v0.7 very soon to at least showcase the improvements.

In a few weeks, I am going to showcase it on a few meetups here in Dublin 😀

**Comment by vadviktor** [comment]
Well, I have started to work on this in a separate branch and now I have run into an issue with colouring. The issue here is that the current colour algorithm is not capable of "nesting". I have found github.com/logrusorgru/aurora to support just that and now am looking into it to adapt that feature.

**Comment by jtyr** [comment]
If nesting is not supported then you must kind of simulate the nesting. The algorithm is not that difficult. You just need to store coloring values into a FILO buffer, then close the current coloring (when a new color is requested), start the new coloring and when the new coloring ends, you restore the original coloring from the buffer and continue.

**Comment by vadviktor** [comment]
@jtyr the context car is already broken apart to user and host. In a closed PR. Needs some cleanup though but I believe master has them.

**Comment by vadviktor** [comment]
@jtyr the context car is already broken apart to user and host. In a closed PR. Needs some cleanup though but I believe master has them.

**Comment by vadviktor** [comment]
@jtyr so that idea is nice, it's just not that simple as I also have to figure out a really good interface, Sprintf preferably to support this. Aldo note filo may not be a throw in and work vector, edge cases like multiple embeds next to each other also have to work. The store and restore approach is similar that came to my mind though. My subconscious will figure this out :stuck_out_tongue:

**Comment by jtyr** [comment]
I would build a tree of the elements and then the processing of it should be easy enough.

**Comment by jtyr** [comment]
I have prototyped it in Python for your inspiration:

```python
#!/usr/bin/python

import re


class Car:
    fg = {
        'default': 39,
        'black': 30,
        'red': 31,
        'green': 32,
        'yellow': 33,
        'blue': 34,
        'magenta': 35,
        'cyan': 36,
        'white': 97,
    }
    bg = {
        'default': 49,
        'black': 40,
        'red': 41,
        'green': 42,
        'yellow': 43,
        'blue': 44,
        'magenta': 45,
        'cyan': 46,
        'white': 107,
    }

    def __init__(self, model, format):
        self.model = model
        self.format = format

    def format_string(self):
        pattern = re.compile('{{\s*(\w+)\s*}}')
        text = ("%s%s%s" % (
            self._color_start('root'), self.format, self._color_end()))

        # Allow element nesting to the depth of 10
        for n in range(10):
            match = pattern.search(text)

            if match:
                text = pattern.sub(self._elemrepl, text)
            else:
                break

        return text

    def _elemrepl(self, matchobj):
        if matchobj.group(1) not in self.model:
            return matchobj.group(0)

        return ("%s%s%s%s" % (
            self._color_end(),
            self._color_start(matchobj.group(1)),
            self._color_end(),
            self._color_start('root')))

    def _color_start(self, element):
        e = self.model[element]

        return ('\x1b[%s;%sm%s' % (
                self._get_fg(e['fg']),
                self._get_bg(e['bg']),
                e['text'] if 'text' in e else ''))

    def _color_end(self):
        return '\x1b[0m'

    def _get_fg(self, name):
        return self.fg[name]

    def _get_bg(self, name):
        return self.bg[name]


def main():
    time_car_model = {
        'root': {
            'bg': 'blue',
            'fg': 'default'
        },
        'Icon': {
            'bg': 'green',
            'fg': 'red',
            'text': '@'
        },
        'DateTime': {
            'bg': 'blue',
            'fg': 'white',
            'text': '{{ Date }} {{ Time }}'
        },
        'Date': {
            'bg': 'blue',
            'fg': 'magenta',
            'text': 'Thu Sep 20'
        },
        'Time': {
            'bg': 'blue',
            'fg': 'white',
            'text': '21:22:23'
        }
    }
    #time_car_format = " x {{ Icon }} {{ Time }} {{ Unknown }} "
    #time_car_format = " x {{ Icon }} {{ Date }} {{ Unknown }} "
    time_car_format = " x {{ Icon }} {{ DateTime }} {{ Unknown }} "
    time_car = Car(time_car_model, time_car_format)

    print(time_car.format_string())


if __name__ == '__main__':
    main()
```

**Comment by vadviktor** [comment]
It could be that the templates and colours eventually end up something as @jtyr suggest the first time. :) Though I am looking into very similar implementations like https://pypi.python.org/pypi/blessings/ and get some already working ideas. It's be nice to have it integrated with solutions like https://github.com/valyala/fasttemplate to gain more speed ;)

**Comment by vadviktor** [comment]
My first iteration will be more explicit as I find too many edge cases to cover with the "intelligent" colouring template. The idea for now is try to use Go template's function call syntax to make explicit colouring readable. Will write some examples later.

**Comment by vadviktor** [comment]
So with using templates I think such a string could be still functional and readable:

The delimiters now configured to be `[` and `]`.

`[.Icon | c ]["some text here" | c "blue:white"][.Info | c]`

In this setup, the `c` is the colour function exposed to the template and it's optional parameter is the colour override. The default colour should be the colour defined for the car itself, that's used when the function `c` does not have a parameter.

The end user may have to type a little bit more, though I don't think that it's cryptic or anyone with just a little shell knowledge or templating background would not be able to comprehend what are the components.

Currently the separator takes the car's default colour and uses that to colour itself. That default colour is also useful to still be set on an env variable level to keep the default colour parameter off from the template AND not having to change the current separator colour logic.

The above template string version is only one of the supported forms of Go's [text/template](https://golang.org/pkg/text/template/#hdr-Examples) package.

**Comment by jtyr** [comment]
How do I override only the colour or the icon symbol if I'm fine with the rest of the car format?

**Comment by vadviktor** [comment]
The icon is still an external info to the template, it's env var is used.

I want a single possie way to do anything here. Your point is valid, how should the colours be overwritten. I feel bad to have env vars for colours and override them elsewhere in the template. Maybe the default colours should be built into the template in this case.
Less env vars, bit longer template to look at, more explicit, less magic.

My concern raised again to be able to easily figure out the car's colour if it would be only in the template.

What if we still define colours in the env vars and use separate template functions to colour variables. 
`c` for car's colour, `cs` for car symbol's and `ci` for car info's colour. The template still could only be used for repositioning and colouring would be told by the user for everything and we won't need weird logic to figure them out.

**Comment by vadviktor** [comment]
I run into a slight problem I didn't think through: how would I describe an icon symbol with spaces around it?

**Comment by vadviktor** [comment]
Alright so it makes sense, there needs to be a second function to be used in the pipeline:

`[.Icon | printf "%s " | cs ][" some text here " | c ][.Info | ci]`

`printf` is a mapping to `fmt.Printf` and acts accordingly. Here we have to use this approach to be able to tell what extra chars to add to the same colouring.
If we would not use this approach, there is a less elegant way too:

`[.Icon | cs ][" " | cs][" some text here " | c ][.Info | ci]`

Though both are valid, I feel there is more mind juggling to the second one.

**Comment by jtyr** [comment]
It doesn't look right. If I cannot configure each bit via env var then I will be forced to redefine the whole template for each car. What if I want to change only one thing? How do I keep in sync with the upstream default template? What people will do is to wrap this nice and fast golang thing into bash and do their magic there which then looses the advantage of even having it written in golang.

**Comment by jtyr** [comment]
You don't even need to use Go templates to make the templating. Have a look at my Python code where I'm parsing the formatting string myself. The only thing which is needed to add is to read the model values from env vars. Simple, fast and variable solution.

**Comment by vadviktor** [comment]
You still define the colours and symbols in env vars. The template is for you to tell where to put which element and what colours to apply to which element.
Please put examples where you feel my last suggestion may falter. Also be reminded that you wanted to see templates in the first place, which I think is a good idea to support every out of the ordinary setup :)

**Comment by jtyr** [comment]
I only want to change icon symbol of icon color. How do I do it without having to define whole car template string?

**Comment by vadviktor** [comment]
I think I was not too clear at first, let me explain:

`.Icon` is an exposed variable holding the default or the symbol defined in the env var, so you are still controlling what symbol appears through the env var. Nothing changed.

`cs` is an exposed function, wrapping the colour setup defined by default or coming from the env var. Nothing changed.

You don't have to change the default template IF you are fine how it arranges the parts themselves.

Is it clearer now? Ask more questions if needed, we have to be on the same line :)

**Comment by vadviktor** [comment]
I'm dogfooding this solution now, and evaluate the usability too.

**Comment by vadviktor** [comment]
Works very well to be honest. I need to do some benchmarks and see if the other library makes it faster without changing the syntax.

**Comment by jtyr** [comment]
OK. So if the symbol as well as the colour of it is as a variable, then why do we need to have that function in the formatting string? It seems to me like unnecessary complication.

Otherwise if you want to add a space behind the icon symbol, which will have the same colour like the symbol, you can add it into the env var instead of re-defining the template.

Let's consider another example. I want to add space at the beginnig of the car, between the Icon and the Info and I want it to have the colour of the car itself. In your formatting it would look like this:

```
CAR_FORMAT='[" " | c ][.Icon | cs ][" " | c ][.Info | ci ]'
```

In a variation of the formatting from my Python example (simply using `[ .. ]` instead of  `{{ ... }}`) it would look like this:

```
CAR_FORMAT=' [ Icon ] [ Info ]'
```

Much simpler. No need to use any functions for colouring.

Just thinking - in your formatting string, do you need to use template for a string of the car colour? Couldn't you simply use just the following?

```
CAR_FORMAT=' [.Icon | cs ] [.Info | ci ]'
```

But even so, the colour function is unnecessary, I think.

**Comment by vadviktor** [comment]
I am merely using what is at my disposal without reinventing the wheel. This is the closest we can get without inventing our own template system and need to rewrite the existing logic how colour setup is drawn for the separators. Right now I don't have to do any hard text parsing, edge case detection and craziness. Go has a great template system which is very much like what you already find out in the wild.

The flaw I have encountered in such design:

`CAR_FORMAT=' [ Icon ] [ Info ]'`

is that when you define the Icon, how do you know what colour is the presiding space and the one that stands in between it and the Info? That is where the expressiveness of the pipeline comes in, it unquestionably tells what to colour.

**Comment by vadviktor** [comment]
I think what you didn't consider is that the car also has a colour, but to apply that colour over the whole -already subcoloured- text is very difficult task. Breaking the text apart again and putting them together...nah, unnecessary programming task.

**Comment by jtyr** [comment]
It's not that difficult. Check the Python example. It does everything you just mentioned (parsing, splitting car colouring, ...). Do you want me to rewrite it in Go so you can just include it? ;o)

**Comment by vadviktor** [comment]
Sorry but what you did in the Python example is not that close how the current Go implementation works. There are some other factors I already taken care of, like calculating the next separator's colour.
By all means, I'd be happy to learn more tricks by reading a cool implementation in Python/Go that uses the same colour format strings and operates with env vars, and you showcase 2-3 cars in action with your idea.

**Comment by jtyr** [comment]
Challenge accepted: https://github.com/jtyr/python_bullet_train

**Comment by vadviktor** [comment]
I see you are really into this @jtyr :grinning:. Let me know when it's ready to have a look and describe your settings for me to copy paste and observe​ it in action. I am truly giving it the base idea a thought and will experiment with it.

**Comment by vadviktor** [comment]
Just reading through the comments and once you suggested a colour template setup yourself:

`{host_short;{context_paint}}`

and that is very close to what the Go templates do.

**Comment by jtyr** [comment]
It's ready. What do you think I was doing till 4am? ;o)

Install it like this:

```bash
git clone https://github.com/jtyr/python_bullet_train.git
cd python_bullet_train
PROMPT='$('$(pwd)'/python_bullet_train.py $?)'
```

Then you can start experimenting with it:

```bash
### Test the Status car
false
true
### Test the Dir car
cd /
cd ~
cd /usr/bin
### Test Sign car
sudo su -
exit
### Test Time car
# Set 12h format
export PBT_CAR_TIME_TIME_FORMAT="%I:%M:%S %p"
# Change background color of the all car
export PBT_CAR_TIME_BG=yellow
# Change color of Date part
export PBT_CAR_TIME_DATE_FG=black
# Reset the color of the Date part
unset PBT_CAR_TIME_DATE_FG
# Reset the background color of all Time car
unset export PBT_CAR_TIME_BG
# Remove the Date part from the car
export PBT_CAR_TIME_FORMAT=" {{ Time }} "
# Reset the format of the car
unset PBT_CAR_TIME_FORMAT
### Train
# Remove the Time car from the train
export PBT_CARS="Status, Hostname, Dir, Sign"
# Reset the original train
unset PBT_CARS
```

Have a look inside the `pbt/cars/*.py` for all possible variables you can use. The latency of the implementation is not as great as if it would be written in Go (perhaps compiling the Python script into a binary would help, let me find out), but the template interface is quite nice and powerful.

**Comment by vadviktor** [comment]
Thanks @jtyr  I'll have a look at it soon. I don't care about performance, that was not the goal. I care to see how you'd implement a better usable template setup with correct colour management and learn as much as I can from it.

**Comment by vadviktor** [comment]
@jtyr I have played around it, broke it 😆 
All in all I got the picture how you thought this through, I'll give it a round and will try to experiment with it.
Handling multibyte chars is also part of the harder problems to figure out, where these chars overlap to the next char space and a space needs to be added. That is not acceptable since the template idea as it will lead to 2 places where positioning is done. The symbol variables should only hold the symbol(s) itself and no spacing (positioning) characters, that is the task of the template.

That regexp is the only thing I will try to play with and try to align the colours still. Thanks for sharing it 👍

**Comment by jtyr** [comment]
How did you break it? ;o)

**Comment by vadviktor** [comment]
I have been thinking about this template thing the past week and came to the following conclusion:

I will keep using the Go template and keep the "simpler" idea in my backlog. It could turn out to be YAGNI and when it does I'll use this idea to simplify.
