### ISSUE TITLE
Plugin Idea

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#31]
What if we have a list of cars that are used, then a user can add a car they wrote to that list. The car can be potentially any language really but we would, of course, recommend go. These plugins are just binaries of some sort, that print something to stdout.

So this is how it would work. User exports BULLETTRAIN_CARS="time date context my_car"

at runtime, we see my_car we look for it internally if it doesn't exist we run bullettrain_my_car binary (they would have to name their plugin a certain way for it to get executed). This then appends info to the prompt? Is this doable?

**Comment by vadviktor** [comment]
This is kinda half of the solution as it won't be able to bring over the colouring.
Unless...a predefined set of ENV vars are also expected. With the suggested naming convention this could work.
I like the idea that it could make use of plugins written in any other language.
I'll work on a prototype given these ideas. Of course ideally we need to be able to tie in unlimited number of "3rd party" cars.

**Comment by jtyr** [comment]
I like the idea.

@vadviktor Are you gonna convert the existing cars into separate binaries?

**Comment by vadviktor** [comment]
@jtyr kinda, absolutely not a chance. :)
I will still encourage Go plugins to be written and used to build into the core /(slash)/ Go knowing individuals being capable to compile their own version. It will be the "officially supported" way to do things.

This other plugin system is a really good alternative to the Go version as it opens up ability for other individuals to use and customise the prompt builder to their liking without knowing Go even. Also a great way of prototyping I guess.
Using this approach will not guarantee the best latency and I will outline that in the docs too.
Making latency as low as possible will be our best promise as I plan to wrap these external commands into a goroutine still and handle the errors there as the code plugins do.

I am very excited to get some free time to create the prototype and the documentation for it.
Also I am sure it is a v1 feature, that we must have. Thanks @gregf for the brilliant idea once again!

**Comment by jtyr** [comment]
Thanks for your explantion, @vadviktor. I also thing that all plugins should be written in Go. But I don't like the idea that people should get their own clone of the core and hack it to get their plugin running. The core should allow to load Go Plugins instead which will not require recompilation of the core.

**Comment by vadviktor** [comment]
@jtyr I'd kindly ask you to learn Go and rethink your proposal :) Please accept the current state of the language ecosystem.

**Comment by vadviktor** [comment]
Here is a proposal for the secondary "3rd party plugin" module:

Name of the plugin: `demo`

## Env variable naming

prefix: `BULLETTRAIN_CAR_PLUGIN_`

suffixes:

| Suffix              | Description                                                                                    | Default value      | Mandatory |
| ------------------- | ---------------------------------------------------------------------------------------------- | ------------------ | --------- |
| `_CMD`              | Command with it's arguments to be executed to generate text onto STDOUT.                       | Creator defined.   | yes       |
| `_SHOW`             | Used by the creator/end user to determine if the plugin should be shown in the current render. | true               | no        |
| `_PAINT`            | Colours of the car.                                                                            | Creator defined.   | yes       |
| `_SYMBOL_ICON`      | Symbol to be displayed on the left hand side of the car.                                       | Creator defined.   | yes       |
| `_SYMBOL_PAINT`     | Colours of the symbol.                                                                         | Creator defined.   | yes       |
| `_SEPARATOR_SYMBOL` | Override the right hand side separator's symbol.                                               | Algorythm defined. | no        |
| `_SEPARATOR_PAINT`  | Override the right hand side separator's colours.                                              | Algorythm defined. | no        |

Example:

`BULLETTRAIN_CAR_PLUGIN_DEMO_SHOW`

## _CMD variable explained

In our example, the `BULLETTRAIN_CAR_PLUGIN_DEMO_CMD` variable will be the heart of the 3rd party plugin.
Here the user will put a very simple command with it's parameters if needed.
No pipes or redirections are supported here to avoid shell subtle differences.
The command has to generate a simple text to the STDOUT. Error handling is the responsibility of the 3rd party script.

### Example Ruby script as a car:

Car name: `demo_ruby`

Put it into the list of cars:

`$ export BULLETTRAIN_CARS="time dir demo_ruby"`

Given that the system has a Ruby interpeter.

hw.rb:

```ruby
print "Hello #{ARGV[0]}"
```

Env variable:

`$ export BULLETTRAIN_CAR_PLUGIN_DEMO_CMD="ruby hw.rb Will"`

After defining the rest of the needed env variables, the output should be displayed as a new car at the end, with the text "Hello Will".

**Comment by vadviktor** [comment]
Check out this dev branch for some preview: https://github.com/bullettrain-sh/bullettrain-go-core/tree/custom_car

I am currently dogfooding this as well. Found a nice little use case, where I just want to check upon my company vpn status, up or down. 

This is my config:

```shell
export BULLETTRAIN_CAR_PLUGIN_RRI_VPN_STATUS_CMD="/home/ikon/rri_vpn_status.sh"
export BULLETTRAIN_CAR_PLUGIN_RRI_VPN_STATUS_PAINT="yellow:black"
export BULLETTRAIN_CAR_PLUGIN_RRI_VPN_STATUS_SYMBOL_ICON="" # <-- key icon from Nerd font
export BULLETTRAIN_CAR_PLUGIN_RRI_VPN_STATUS_SYMBOL_PAINT="yellow:black"
export BULLETTRAIN_CARS="os time date context dir python go ruby nodejs php git rri_vpn_status status"
```

and the plain simple shell script:

```shell
#!/bin/zsh

if [[ $(ip tuntap list | wc -l) -gt 0 ]]; then
    echo -n "up"
else
    echo -n "down"
fi
```

With this, I faced a limitation when I wanted to "dynamically" paint the key red or green depending on the status. Not doable yet :(

**Comment by vadviktor** [comment]
# Note

the support for a plugin command is very basic. I was not able to figure out a fault tolerant way to handle such cases where a command line argument would need to be quoted:

`somecmd --arg -p "hello world"`

For now, arguments without quotes are supported. Anything fancier should go into a file to be parsed, like in my example in the above comment.

**Comment by jtyr** [comment]
Couldn't you change the color somehow via subshell?

```
export BULLETTRAIN_CAR_PLUGIN_RRI_VPN_STATUS_SYMBOL_PAINT="$(if [[ $(/home/ikon/rri_vpn_status.sh) == 'up' ]]; then echo yellow:black; else echo red:black; fi)"
```

**Comment by vadviktor** [comment]
Changing the properties within a plugin command is not possible, because it will run as a sub process/thread. Changing env variables for the parent is not possible.

**Comment by vadviktor** [comment]
As an afterthought, I may not even go further to make it possible because this plugin support is only secondary to the Go version, and therefore low priority.

**Comment by jtyr** [comment]
You are right. What about to identify the `^\$\(.*\)$` in the variable value and run it from the car process as a shell command?

**Comment by vadviktor** [comment]
This is only a neat feature I was looking at  while I am using the plugin myself, not as blocking problem to deliver the plugin feature. :)
A few more days and I could decide if this form of the "custom car" feature is stable enough. And maybe I get some reports from you guys :) just keep an eye out for commits ;)

**Comment by jtyr** [comment]
I have just noticed that the depth indicator set to 1 in the dir car doesn't produce the desired output.

**Comment by vadviktor** [comment]
@jtyr please submit a ticket with examples and more info :) I will surely look into it as I have spent so much time testing it. Since then it Works For Me ™️ XD

**Comment by vadviktor** [comment]
Closing the current thread as the first working version went into the new v0.6 release.
