### ISSUE TITLE
Custom seperator for directory car

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#32]
Allow the user to customize the separator for the directory car, so each directory can appear as a segment. Possibly enable this by default, I personally think it looks good from a ux stand point.

**Comment by vadviktor** [comment]
Yep, first I'd think we should just try to be able to define the directory separator. Then iterate on that further if needed.

**Comment by vadviktor** [comment]
Looks good so far 😄 

![spectacle m22908](https://user-images.githubusercontent.com/238703/29751466-904fa746-8b45-11e7-8788-81feb49516d5.png)

**Comment by vadviktor** [comment]
@gregf I'd need some opinion on the case when the path is too long and the first ones are chopped off:

![spectacle j233df78](https://user-images.githubusercontent.com/238703/29751504-36b2f322-8b46-11e7-9203-a27498dc37ba.png)

Any ideas if this looks good enough or are there any other examples I can copy? Thanks!

**Comment by gregf** [comment]
@vadviktor LGTM

**Comment by gregf** [comment]
It shouldn't print the separator for the first element. It looks weird with my setup.

![path](https://user-images.githubusercontent.com/980/29752282-05fd6824-8b29-11e7-8b0f-2ad554278a90.jpg)

**Comment by vadviktor** [comment]
I see. This will need way more UX thinking. Somehow the user needs to know especially on a *nix system where the root folder starts if it is displayed.

**Comment by vadviktor** [comment]
@jtyr if you have any good idea to put in here, I'd be really interested to hear :)

**Comment by gregf** [comment]
I think your solution will work. I also think this should be the deafult UX. It's standard in a lot of the cooler prompts these days. I think it looks a lot nicer personally.

**Comment by jtyr** [comment]
I think all the ideas here are good. We already have the variable for different directory separator  (`BULLETTRAIN_CAR_DIRECTORY_SEPARATOR_SYMBOL="/"`). I would just introduce another two variables to disable showing the first directory separator (`BULLETTRAIN_CAR_DIRECTORY_SEPARATOR_SYMBOL_SKIP_FIRST="false"`) and allow to always show  the first bit of the path (`BULLETTRAIN_CAR_DIRECTORY_SHOW_FIRST_ALWAYS="true"`). I would also consider to separate all the cars into separate Git repos.

**Comment by vadviktor** [comment]
Ok, so it's not only me who is thinking about breaking out ALL the cars into their own repo :)

Back to the UX stuff. Yes I can see a use case for `BULLETTRAIN_CAR_DIRECTORY_SEPARATOR_SYMBOL_SKIP_FIRST`.
Also `BULLETTRAIN_CAR_DIRECTORY_SHOW_FIRST_ALWAYS` sounds a good option, it should kick in near `BULLETTRAIN_CAR_DIRECTORY_DEPTH_INDICATOR`.

**Comment by vadviktor** [comment]
Just a side fun stuff: there are going to be soooo much settings and switches and whistles, I will create a simple config generator web interface (Go naturally) that can be used to generate the variables ready to be copy pasted :)

**Comment by jtyr** [comment]
That sounds cool although a bit complicated. I would just maybe create a directory with themes. Something like oh-my-zsh has [here](https://github.com/robbyrussell/oh-my-zsh/wiki/themes). Then the user would just `source` a specific theme and could override specific vars to fine-tune it.

**Comment by vadviktor** [comment]
Themes are another stuff, this tool is just for the end user to faster click together the config without too many copy-pasting. But this is another story and just for my amusement mainly, where I can learn some web dev in Go.

**Comment by jtyr** [comment]
In that case, pure JS implementation would be better as it would be real-time solution.

**Comment by gregf** [comment]
I have to agree javascript is the way to go. Look at Angular imo

**Comment by vadviktor** [comment]
Please have a look at the updates here 1d6529e. It's not the nicest code yet, but good for a feature review.

**Comment by vadviktor** [comment]
Implemented. New tickets will cover further customisations and fixes.
