### ISSUE TITLE
Give feedback on not found

### ISSUE THREAD

**Issue by vadviktor** [bullettrain-sh/bullettrain-go-core#38]
For cars like python, nodejs, etc which try to execute a command line call and if the command does not exist, only the car's background is visible.
All these need to have a default text, like `[_._._]` displayed, or something. When debug mode is on (`BULLETTRAIN_DEBUG=true`), then kindly put the problem in the text, like command not found.

**Comment by gregf** [comment]
Personally, I think if the command isn't found we should display that in its place. It should print the background with text saying "Nodejs cmd not found" or something similar. It's a clear message as to what's wrong and they don't have to go through the steps of enabling debugging to figure it out.

**Comment by vadviktor** [comment]
The problem with just putting whatever error there was is that sometimes it may be multiple lines and vastly long.
I'd be happy that the Car's author makes a small, few words note as the text, saying like "No PHP found".
The debug version then could be more verbose, I don't care since it's debug mode, the author can join the long message into a single line too.
How's that?

**Comment by gregf** [comment]
Yeah i wasn't saying display stderr. If the command is not found, print a nice message.

**Comment by vadviktor** [comment]
I have added the error message directly from the command for some cars, others will follow.
