### ISSUE TITLE
Max length in Dir car doesn't work as expected

### ISSUE THREAD

**Issue by jtyr** [bullettrain-sh/bullettrain-go-core#41]
I would expect that this configuration:

```shell
export BULLETTRAIN_CAR_DIRECTORY_MAX_LENGHT='1'
export BULLETTRAIN_CAR_DIRECTORY_DEPTH_INDICATOR=''
export BULLETTRAIN_CAR_DIRECTORY_PATH_SEPARATOR='/'
export BULLETTRAIN_CAR_DIRECTORY_FIRST_DIR_SHOW='false'
```

when in `/usr/share/man/man3` will show only `man3`.

**Comment by vadviktor** [comment]
Undocumented as it is, max dir length is set to be no less then 3 at the moment. Having so many factors playing in how the dir path is rendered, I chose not to drag myself down with figuring every edge case out right now. After V1 I'll find time to making it more customisable. (Or I could get a PR) :)

**Comment by vadviktor** [comment]
Thanks for the PR @jtyr , I closed it for now as it made me realise there is more to this problem that a single PR solves. First I will go back to the drawing board and sketch up a logic proposal, covering the variables too.

**Comment by jtyr** [comment]
No problem. I look forward to see the correct implementation.

**Comment by vadviktor** [comment]
I am also thinking about automatic resizing of the directory path, like I have seen in one of the powershell like prompts. Though I can't find it anymore to take ideas from it, I thought to use `tput cols` and/or `stty size` commands to get the width of the shell. The idea I am missing is, how to determine the breakpoints like in responsive web design.

Any ideas @jtyr @gregf @caiogondim ?

**Comment by jtyr** [comment]
You can use the shell variable `$COLUMNS` for that. And then based on the width of the terminal, add `\n` behind some of the cars.

**Comment by vadviktor** [comment]
`$COLUMNS` is in BASH only. 

Here I am not looking to add new lines, but to determine how much directories to print in the path. Say, you are seeing 2 directories at width 80, then you start to resize the term to 120. During resizing you start to see more and more directories being rendered, at the end (width 120) you'll see e.g. 5 directories in the path. Just like what you'll experience with resizing the browser on a responsive html page.

The recipe for those column breakpoints is what I am looking for.

**Comment by jtyr** [comment]
`$COLUMNS` exists also in ZSH.

**Comment by vadviktor** [comment]
For some reason (I am no shell expert) it is not shown in the `env` list but true enough, when echoed, it has a value.

**Comment by vadviktor** [comment]
I have added tests and reworked a bit how the directory car is configured. https://github.com/bullettrain-sh/bullettrain-go-core/tree/v0.8
