### ISSUE TITLE
Master broken with bash

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#43]
Prompt is really messed up on master with bash

![prompt](https://user-images.githubusercontent.com/980/30257949-64cf2b84-9683-11e7-87ec-12870315164d.jpg)

**Comment by vadviktor** [comment]
Yes, I have a hard time to figure out how to put the bash version non printing chars in the output. #17 Bash may have bugs when v1 is released. I am happy to fully support at least 1 shell.

**Comment by vadviktor** [comment]
Those non printing chars you see `%{` and `%}` are for ZSH and BASH uses fecked up `\[` and `\]` where the biggest problem is to get that escaping backslash right.

**Comment by vadviktor** [comment]
I decided to leave BASH support out from the v1 release, I just can't yet figure out how to properly handle those invisible characters down to BASH.

**Comment by vadviktor** [comment]
Axing bash support for now.
