### ISSUE TITLE
irc channel

### ISSUE THREAD

**Issue by gregf** [bullettrain-sh/bullettrain-go-core#7]
How about we create an IRC channel on Freenode so we can talk in real time and work on this? I created #bullettrain if you want to meet me there or just /query gregf and we'll talk.

**Comment by vadviktor** [comment]
I guess I beat you there with #bullettrain-sh. :) I wonder which name would be most appropriate. @caiogondim  ?

**Comment by ThamosIO** [comment]
Why not a slack team instead ?

**Comment by vadviktor** [comment]
@ThamosIO there is a Slack team also, it's just that IRC is still a huge defacto for developers that I'd like to have a presence there. I'd also like to be able to hook IRC and Slack up together somehow.

**Comment by caiogondim** [comment]
I like `#bullettrain-sh` 👍

**Comment by gregf** [comment]
I'm not picky, just wanted irc. You won't catch me on slack personally.

**Comment by caiogondim** [comment]
+1 for iRC

**Comment by vadviktor** [comment]
@gregf @caiogondim I just want to make sure which irc channel name we choose as I want to go ahead and register the channel with freenode. Are we sticking to `bullettrain-sh` as the organisation name suggests?

**Comment by gregf** [comment]
Doesn't matter to me just let me know where to be. :)

**Comment by caiogondim** [comment]
Let's go with `#bullettrain-sh`
